// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Creates a blank, fully transparent canvas of `width` x `height` pixels.
/// Returns NULL if `width`/`height` are not positive or on allocation failure.
@ffi.Native<ffi.Pointer<LcImage> Function(ffi.Int32, ffi.Int32)>()
external ffi.Pointer<LcImage> lc_image_create(int width, int height);

/// Releases a canvas created by lc_image_create. Passing NULL is a no-op.
@ffi.Native<ffi.Void Function(ffi.Pointer<LcImage>)>()
external void lc_image_destroy(ffi.Pointer<LcImage> image);

/// Fills the whole canvas with a solid ARGB color (0xAARRGGBB).
@ffi.Native<ffi.Void Function(ffi.Pointer<LcImage>, ffi.Uint32)>()
external void lc_image_clear(ffi.Pointer<LcImage> image, int argb);

/// Encodes the canvas as PNG into a newly allocated buffer, written to
/// `*out_data`/`*out_len`. Returns 0 on success, non-zero on failure. On
/// success, the caller must release the buffer with lc_buffer_free.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<LcImage>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int lc_image_encode_png(
  ffi.Pointer<LcImage> image,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
  ffi.Pointer<ffi.Size> out_len,
);

/// Releases a buffer produced by lc_image_encode_png. Passing NULL is a
/// no-op.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>()
external void lc_buffer_free(ffi.Pointer<ffi.Uint8> data);

/// Composes a whole scene in one call: creates a `width` x `height` canvas,
/// paints `layers` onto it in array order, and encodes the result as
/// `format` (LcOutputFormat) into `*out_data`/`*out_len`. Returns 0 on
/// success. On success, the caller must release the buffer with
/// lc_buffer_free.
///
/// The caller (the Dart side) is responsible for resolving stacking order
/// (Layer.zIndex) into `layers`' array order and dropping invisible layers
/// before calling this - see scene_desc.h. `layers` may be NULL only if
/// `layer_count` is 0.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<LcLayerDesc>,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int lc_render_scene(
  int width,
  int height,
  ffi.Pointer<LcLayerDesc> layers,
  int layer_count,
  int format,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
  ffi.Pointer<ffi.Size> out_len,
);

/// Registers `data_size` bytes of font data (TTF/OTF) under `name` and
/// `weight` (100..900, CSS/OpenType scale), so any TextLayer whose
/// fontFamily equals `name` renders with whichever registered weight is
/// closest to its own fontWeight. A family may have several weights
/// registered under the same `name`; registering the same `name`+`weight`
/// again replaces only that variant. Registration is global and persists
/// for the lifetime of the process (or until lc_font_unregister is called)
/// — it is not tied to any single Scene or render call. `data` is copied;
/// the caller may free it as soon as this function returns. Returns 0 on
/// success.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int lc_font_register(
  ffi.Pointer<ffi.Char> name,
  int weight,
  ffi.Pointer<ffi.Uint8> data,
  int data_size,
);

/// Removes the font previously registered under `name`+`weight`. Returns 0
/// if found and removed, 1 if no font was registered under that exact
/// name+weight pair. Other weights registered under the same `name` are
/// unaffected.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Int32)>()
external int lc_font_unregister(ffi.Pointer<ffi.Char> name, int weight);

/// Wire format for a single layer, shared between the public FFI surface
/// (engine.h) and every backend implementation (backend.h). This is *our*
/// generic scene description, not tied to any graphics library.
///
/// The Dart side is responsible for:
/// - resolving stacking order (Layer.zIndex) into plain array order,
/// - dropping invisible layers,
/// - flattening the common Layer.transform/size/opacity into these fields.
/// A backend only ever sees a flat array of these and never needs to know
/// about Scene, Layer, or Dart at all.
///
/// Adding a new renderable layer kind means adding a value to LcLayerKind,
/// adding its dedicated fields below, and teaching a backend's render_layers
/// to handle the new kind - engine.h's function signature never changes.
enum LcLayerKind {
  LC_LAYER_KIND_UNKNOWN(0),
  LC_LAYER_KIND_RECTANGLE(1),
  LC_LAYER_KIND_TEXT(2),
  LC_LAYER_KIND_IMAGE(3),
  LC_LAYER_KIND_PATH(4);

  final int value;
  const LcLayerKind(this.value);

  static LcLayerKind fromValue(int value) => switch (value) {
    0 => LC_LAYER_KIND_UNKNOWN,
    1 => LC_LAYER_KIND_RECTANGLE,
    2 => LC_LAYER_KIND_TEXT,
    3 => LC_LAYER_KIND_IMAGE,
    4 => LC_LAYER_KIND_PATH,
    _ => throw ArgumentError('Unknown value for LcLayerKind: $value'),
  };
}

/// Encoded output formats a rendered canvas can be requested as (mirrors
/// lib/src/renderer/renderer.dart's OutputFormat, same declared order).
/// Deliberately no JPEG: this vendored Blend2D's JPEG codec only implements
/// decoding - encode_create_encoder returns BL_ERROR_IMAGE_ENCODER_NOT_PROVIDED
/// (see codec/jpegcodec.cpp), so it's not a usable output format today.
enum LcOutputFormat {
  LC_OUTPUT_FORMAT_PNG(0),
  LC_OUTPUT_FORMAT_BMP(1),
  LC_OUTPUT_FORMAT_QOI(2);

  final int value;
  const LcOutputFormat(this.value);

  static LcOutputFormat fromValue(int value) => switch (value) {
    0 => LC_OUTPUT_FORMAT_PNG,
    1 => LC_OUTPUT_FORMAT_BMP,
    2 => LC_OUTPUT_FORMAT_QOI,
    _ => throw ArgumentError('Unknown value for LcOutputFormat: $value'),
  };
}

/// Paint (fill/stroke source) kinds a shape can request. Kept as its own
/// type - decoupled from any specific shape's fields below - so future
/// geometry kinds (circles, paths...) can reuse LcPaintDesc verbatim instead
/// of growing per-shape color fields, and so this enum can later grow e.g.
/// LC_PAINT_KIND_PATTERN without touching existing call sites.
enum LcPaintKind {
  LC_PAINT_KIND_SOLID(0),
  LC_PAINT_KIND_LINEAR_GRADIENT(1),
  LC_PAINT_KIND_RADIAL_GRADIENT(2),
  LC_PAINT_KIND_CONIC_GRADIENT(3);

  final int value;
  const LcPaintKind(this.value);

  static LcPaintKind fromValue(int value) => switch (value) {
    0 => LC_PAINT_KIND_SOLID,
    1 => LC_PAINT_KIND_LINEAR_GRADIENT,
    2 => LC_PAINT_KIND_RADIAL_GRADIENT,
    3 => LC_PAINT_KIND_CONIC_GRADIENT,
    _ => throw ArgumentError('Unknown value for LcPaintKind: $value'),
  };
}

/// How a gradient behaves outside its defined 0..1 offset range. Only
/// meaningful when LcPaintDesc.kind is one of the *_GRADIENT kinds above.
enum LcExtendMode {
  LC_EXTEND_MODE_PAD(0),
  LC_EXTEND_MODE_REPEAT(1),
  LC_EXTEND_MODE_REFLECT(2);

  final int value;
  const LcExtendMode(this.value);

  static LcExtendMode fromValue(int value) => switch (value) {
    0 => LC_EXTEND_MODE_PAD,
    1 => LC_EXTEND_MODE_REPEAT,
    2 => LC_EXTEND_MODE_REFLECT,
    _ => throw ArgumentError('Unknown value for LcExtendMode: $value'),
  };
}

/// Shape of a stroke's open ends (mirrors lib/src/model/paint.dart's
/// StrokeCap, same declared order). Only meaningful for a stroked paint.
enum LcStrokeCap {
  LC_STROKE_CAP_BUTT(0),
  LC_STROKE_CAP_ROUND(1),
  LC_STROKE_CAP_SQUARE(2);

  final int value;
  const LcStrokeCap(this.value);

  static LcStrokeCap fromValue(int value) => switch (value) {
    0 => LC_STROKE_CAP_BUTT,
    1 => LC_STROKE_CAP_ROUND,
    2 => LC_STROKE_CAP_SQUARE,
    _ => throw ArgumentError('Unknown value for LcStrokeCap: $value'),
  };
}

/// Shape drawn where two stroked segments meet (mirrors
/// lib/src/model/paint.dart's StrokeJoin, same declared order). Only
/// meaningful for a stroked paint.
enum LcStrokeJoin {
  LC_STROKE_JOIN_MITER(0),
  LC_STROKE_JOIN_ROUND(1),
  LC_STROKE_JOIN_BEVEL(2);

  final int value;
  const LcStrokeJoin(this.value);

  static LcStrokeJoin fromValue(int value) => switch (value) {
    0 => LC_STROKE_JOIN_MITER,
    1 => LC_STROKE_JOIN_ROUND,
    2 => LC_STROKE_JOIN_BEVEL,
    _ => throw ArgumentError('Unknown value for LcStrokeJoin: $value'),
  };
}

/// A single color stop within a gradient's ramp. `offset` is 0..1 along the
/// gradient (mirrors lib/src/model/gradient.dart's GradientStop).
final class LcGradientStop extends ffi.Struct {
  @ffi.Double()
  external double offset;

  @ffi.Uint32()
  external int color_argb;
}

/// Describes what to paint a shape's fill/stroke with - a solid color or a
/// gradient - independent of the shape's own geometry (mirrors
/// lib/src/model/paint.dart's LayerPaint/Gradient split). Embedded by value
/// inside a shape's fields below (e.g. LcLayerDesc.rect_paint).
final class LcPaintDesc extends ffi.Struct {
  /// LcPaintKind
  @ffi.Int32()
  external int kind;

  /// meaningful when kind == LC_PAINT_KIND_SOLID.
  @ffi.Uint32()
  external int solid_color_argb;

  /// LcExtendMode; meaningful for gradient kinds only.
  @ffi.Int32()
  external int extend_mode;

  /// Gradient geometry, fractional (0..1) relative to the painted shape's
  /// own width/height - meaning depends on `kind`:
  /// LINEAR_GRADIENT: x0, y0, x1, y1   (start point, end point)
  /// RADIAL_GRADIENT: cx, cy, radius   (center point, radius; values[3]
  /// unused)
  /// CONIC_GRADIENT:  cx, cy, angle    (center point, start angle in
  /// radians; values[3] unused)
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Double> values;

  /// Gradient stops - option (b): pointer + count, same ownership pattern as
  /// LcLayerDesc.image_data/image_data_size below. Owned by the caller for
  /// the duration of a single lc_render_scene call only; meaningful for
  /// gradient kinds only (NULL/0 when kind == LC_PAINT_KIND_SOLID).
  external ffi.Pointer<LcGradientStop> stops;

  @ffi.Int32()
  external int stop_count;

  /// LcStrokeCap
  @ffi.Int32()
  external int stroke_cap;

  /// LcStrokeJoin
  @ffi.Int32()
  external int stroke_join;

  @ffi.Double()
  external double stroke_miter_limit;
}

/// A single step of a PathLayer's geometry (mirrors lib/src/model/path.dart's
/// PathCommand). Each command consumes a fixed number of doubles from the
/// parallel LcLayerDesc.path_coords array below:
/// MOVE_TO/LINE_TO: 1 point (2 doubles: x, y)
/// QUAD_TO:         2 points (4 doubles: control, end)
/// CUBIC_TO:        3 points (6 doubles: control1, control2, end)
/// ARC_TO:          7 doubles: rx, ry, x_axis_rotation (radians),
/// large_arc (0.0/1.0), sweep (0.0/1.0), end x, end y -
/// same endpoint parameterization as SVG's `A`/`a` path
/// command. The flags are packed as doubles (rather than
/// giving ARC_TO a different stride/type in path_coords)
/// so every command can be walked the same way: read N
/// doubles, where N depends only on the command byte.
/// CLOSE:           0 doubles.
enum LcPathCommand {
  LC_PATH_COMMAND_MOVE_TO(0),
  LC_PATH_COMMAND_LINE_TO(1),
  LC_PATH_COMMAND_QUAD_TO(2),
  LC_PATH_COMMAND_CUBIC_TO(3),
  LC_PATH_COMMAND_CLOSE(4),
  LC_PATH_COMMAND_ARC_TO(5);

  final int value;
  const LcPathCommand(this.value);

  static LcPathCommand fromValue(int value) => switch (value) {
    0 => LC_PATH_COMMAND_MOVE_TO,
    1 => LC_PATH_COMMAND_LINE_TO,
    2 => LC_PATH_COMMAND_QUAD_TO,
    3 => LC_PATH_COMMAND_CUBIC_TO,
    4 => LC_PATH_COMMAND_CLOSE,
    5 => LC_PATH_COMMAND_ARC_TO,
    _ => throw ArgumentError('Unknown value for LcPathCommand: $value'),
  };
}

/// How overlapping/self-intersecting regions of a PathLayer are filled
/// (mirrors lib/src/model/path.dart's FillRule). Only meaningful for fills;
/// ignored for a stroke-only paint.
enum LcFillRule {
  LC_FILL_RULE_NON_ZERO(0),
  LC_FILL_RULE_EVEN_ODD(1);

  final int value;
  const LcFillRule(this.value);

  static LcFillRule fromValue(int value) => switch (value) {
    0 => LC_FILL_RULE_NON_ZERO,
    1 => LC_FILL_RULE_EVEN_ODD,
    _ => throw ArgumentError('Unknown value for LcFillRule: $value'),
  };
}

final class LcLayerDesc extends ffi.Struct {
  /// Common properties, shared by every layer kind (mirrors lib/src/model/
  /// layer.dart and transform.dart).
  @ffi.Double()
  external double pos_x;

  @ffi.Double()
  external double pos_y;

  @ffi.Double()
  external double width;

  @ffi.Double()
  external double height;

  /// radians
  @ffi.Double()
  external double rotation;

  @ffi.Double()
  external double scale_x;

  @ffi.Double()
  external double scale_y;

  /// fractional, 0..1 of width/height
  @ffi.Double()
  external double anchor_x;

  @ffi.Double()
  external double anchor_y;

  /// 0..1
  @ffi.Double()
  external double opacity;

  /// LcLayerKind. Backends must ignore kinds they don't
  /// recognize instead of failing the whole render.
  @ffi.Int32()
  external int kind;

  /// shared by both fill and stroke below.
  external LcPaintDesc rect_paint;

  /// 0 = fill, 1 = stroke, 2 = fillAndStroke
  @ffi.Int32()
  external int rect_paint_style;

  @ffi.Double()
  external double rect_stroke_width;

  @ffi.Double()
  external double rect_corner_radius;

  /// UTF-8, NOT null-terminated.
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Uint8> text;

  /// valid bytes in `text`, 0..LC_TEXT_MAX_BYTES.
  @ffi.Int32()
  external int text_length;

  @ffi.Double()
  external double text_font_size;

  @ffi.Uint32()
  external int text_color_argb;

  /// 0 = left, 1 = center, 2 = right.
  @ffi.Int32()
  external int text_align;

  /// 100..900 (CSS/OpenType scale); backend buckets this
  @ffi.Int32()
  external int text_weight;

  /// UTF-8, NOT null-terminated.
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Uint8> font_family;

  /// valid bytes in `font_family`.
  @ffi.Int32()
  external int font_family_length;

  /// ImageLayer-specific fields (meaningful only when kind ==
  /// LC_LAYER_KIND_IMAGE). Mirrors lib/src/model/layers/image_layer.dart.
  ///
  /// `image_data` points to `image_data_size` bytes of *encoded* image data
  /// (PNG/JPEG/BMP/QOI - detected automatically by Blend2D). Unlike `text`
  /// and `font_family` above, this isn't embedded inline: images range from
  /// a few KB to several MB, far past a fixed-size buffer. The pointer is
  /// owned by the caller for the duration of a single lc_render_scene call
  /// only; the backend must not retain it afterward.
  external ffi.Pointer<ffi.Uint8> image_data;

  @ffi.Int32()
  external int image_data_size;

  /// 0 = fill, 1 = contain, 2 = cover, 3 = none.
  @ffi.Int32()
  external int image_fit;

  /// PathLayer-specific fields (meaningful only when kind ==
  /// LC_LAYER_KIND_PATH). Mirrors lib/src/model/layers/path_layer.dart.
  ///
  /// Unlike rect_paint's gradient geometry (fractional, relative to
  /// width/height), path_coords below are absolute, in this layer's own
  /// local space - the same origin (0,0) RectangleLayer's own geometry
  /// uses. path_paint is still reused verbatim from LcPaintDesc: a
  /// gradient's own geometry inside it stays fractional relative to
  /// width/height regardless of what shape it's painting.
  external LcPaintDesc path_paint;

  /// 0 = fill, 1 = stroke, 2 = fillAndStroke
  @ffi.Int32()
  external int path_paint_style;

  @ffi.Double()
  external double path_stroke_width;

  /// LcFillRule
  @ffi.Int32()
  external int path_fill_rule;

  /// one LcPathCommand byte per entry.
  external ffi.Pointer<ffi.Uint8> path_commands;

  @ffi.Int32()
  external int path_command_count;

  /// flattened x,y pairs, consumed in order as
  external ffi.Pointer<ffi.Double> path_coords;

  /// total doubles in path_coords.
  @ffi.Int32()
  external int path_coord_count;
}

final class LcImage extends ffi.Opaque {}

const int LC_TEXT_MAX_BYTES = 1024;

const int LC_FONT_FAMILY_MAX_BYTES = 64;
